const defaultLibrary = [
    { id: 1, title: "Harry Potter (Hedwig's Theme)", code: "hp", notes: "1 4 5# 5 4 7# 6# 5 1 4 5# 5 4 1+" },
    { id: 2, title: "Karayip Korsanları", code: "poc", notes: "1 1 2 2 2 3 4 4 4 5 3 3 2 1 1 2" },
    { id: 3, title: "The Godfather", code: "gf", notes: "3 6 1+ 7 6 1+ 6 7 6 4 5 3" },
    { id: 4, title: "Neşeye Övgü (Ode to Joy)", code: "oj", notes: "3 3 4 5 5 4 3 2 1 1 2 3 3 2 2" },
    { id: 5, title: "Game of Thrones", code: "got", notes: "6 2+ 4+ 5+ 6 2+ 4+ 5+ 6" },
    { id: 6, title: "Star Wars", code: "sw", notes: "1 5 4 3 2 1+ 5 4 3 2 1+ 5 4 3 4 2" },
    { id: 7, title: "Megalovania", code: "mega", notes: "2 2 2+ 6 6b 5 4 2 4 5" }
];

let setlist = [];

const libraryList = document.getElementById("library-list");
const setlistContainer = document.getElementById("setlist");

function renderLibrary() {
    libraryList.innerHTML = "";
    defaultLibrary.forEach(song => {
        const div = document.createElement("div");
        div.className = "song-item";
        div.innerHTML = `
            <div class="song-info">
                <h4>${song.title}</h4>
                <p>Kısa Kod: !${song.code}</p>
            </div>
            <button onclick="addToSetlist(${song.id})">Ekle</button>
        `;
        libraryList.appendChild(div);
    });
}

function renderSetlist() {
    setlistContainer.innerHTML = "";
    if (setlist.length === 0) {
        setlistContainer.innerHTML = `<p class="empty-msg">Kütüphaneden şarkı seçin...</p>`;
        return;
    }

    setlist.forEach((song, index) => {
        const div = document.createElement("div");
        div.className = "song-item";
        div.innerHTML = `
            <div class="song-info">
                <h4>${song.title}</h4>
                <p>Kısa Kod: !${song.code}</p>
            </div>
            <button onclick="removeFromSetlist(${index})">Kaldır</button>
        `;
        setlistContainer.appendChild(div);
    });
}

// Make functions globally accessible for inline onclick
window.addToSetlist = addToSetlist;
window.removeFromSetlist = removeFromSetlist;

function addToSetlist(id) {
    const song = defaultLibrary.find(s => s.id === id);
    if (song && !setlist.find(s => s.title === song.title)) {
        setlist.push(song);
        renderSetlist();
    }
}

function removeFromSetlist(index) {
    setlist.splice(index, 1);
    renderSetlist();
}

document.getElementById("btn-add-custom").addEventListener("click", () => {
    const title = document.getElementById("custom-title").value.trim();
    const code = document.getElementById("custom-code").value.trim();
    const notes = document.getElementById("custom-notes").value.trim();

    if (!title || !code || !notes) {
        alert("Lütfen tüm alanları doldurun.");
        return;
    }

    const newSong = { id: Date.now(), title, code, notes };
    defaultLibrary.push(newSong);
    renderLibrary();
    document.getElementById("custom-title").value = "";
    document.getElementById("custom-code").value = "";
    document.getElementById("custom-notes").value = "";
});

function generateAHK() {
    if (setlist.length === 0) {
        alert("Lütfen setliste en az bir şarkı ekleyin.");
        return;
    }

    const speed = document.getElementById("play-speed").value || 300;
    
    let ahkScript = "; Neverwinter Bard Master AHK Script\\n";
    ahkScript += "; Generated by Bard Master\\n\\n";
    ahkScript += "#NoEnv\\n";
    ahkScript += "SendMode Input\\n";
    ahkScript += "SetWorkingDir %A_ScriptDir%\\n\\n";

    setlist.forEach(song => {
        ahkScript += `::!${song.code}::\\n`;
        const notesArr = song.notes.trim().split(/\\s+/);
        
        notesArr.forEach(note => {
            let key = note;
            let modifier = "";
            let modUp = "";
            
            if (note.includes("#") || note.includes("↑")) {
                key = note.replace(/#|↑/g, "");
                modifier = "{Up down}";
                modUp = "{Up up}";
            } else if (note.includes("b") || note.includes("↓")) {
                key = note.replace(/b|↓/g, "");
                modifier = "{Down down}";
                modUp = "{Down up}";
            } else if (note.includes("+")) {
                key = note.replace(/\\+/g, "");
                modifier = "{Right down}";
                modUp = "{Right up}";
            } else if (note.includes("-")) {
                key = note.replace(/\\-/g, "");
                modifier = "{Left down}";
                modUp = "{Left up}";
            }

            if (modifier) {
                ahkScript += `Send ${modifier}{${key}}${modUp}\\n`;
            } else {
                ahkScript += `Send {${key}}\\n`;
            }
            ahkScript += `Sleep ${speed}\\n`;
        });
        ahkScript += "return\\n\\n";
    });

    const blob = new Blob([ahkScript], { type: "text/plain;charset=utf-8" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "BardMaster.ahk";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}

document.getElementById("btn-generate").addEventListener("click", generateAHK);

// Init
renderLibrary();
